Experiment 15

Data Normalization and Data Type Conversion

Part A: Data Normalization

shrirang lakhpurkar
PRN:25070123108

In [ ]:
#dataset

import pandas as pd
import numpy as np
data = {
    'Product': ['Laptop', 'Mobile', 'Tablet', 'Headphones', 'Smartwatch', 'Camera'],
    'Price': [55000, 20000, 30000, 2000, 8000, 45000],
    'Units_Sold': [25, 60, 35, 80, 50, 15],
    'Discount':[10,15,12,20,18,8]
}
df=pd.DataFrame(data)
print(df)

      Product  Price  Units_Sold  Discount
0      Laptop  55000          25        10
1      Mobile  20000          60        15
2      Tablet  30000          35        12
3  Headphones   2000          80        20
4  Smartwatch   8000          50        18
5      Camera  45000          15         8

In [ ]:
#min max normalization
#min max normalization for price
df['Price_MinMax']=(df['Price']-df['Price'].min())/(df['Price'].max()-df['Price'].min())
print(df[['Product','Price','Price_MinMax']])
#all columns can be done together

      Product  Price  Price_MinMax
0      Laptop  55000      1.000000
1      Mobile  20000      0.339623
2      Tablet  30000      0.528302
3  Headphones   2000      0.000000
4  Smartwatch   8000      0.113208
5      Camera  45000      0.811321

In [ ]:
#normalizing multiple columns
cols=['Price','Units_Sold','Discount']
df_norm=(df[cols] - df[cols].min())/(df[cols].max()-df[cols].min())
print(df_norm)
#normalization coverts the value between 1 to 0

      Price  Units_Sold  Discount
0  1.000000    0.153846  0.166667
1  0.339623    0.692308  0.583333
2  0.528302    0.307692  0.333333
3  0.000000    1.000000  1.000000
4  0.113208    0.538462  0.833333
5  0.811321    0.000000  0.000000

In [ ]:
#z sore optimization
#handles outliers x-xmin/xs+d
#deals with outliers
df['Unit_ZScore']=(df['Units_Sold']-df['Units_Sold'].mean())/df['Units_Sold'].std()
print(df[['Product','Units_Sold','Unit_ZScore']])

      Product  Units_Sold  Unit_ZScore
0      Laptop          25    -0.799885
1      Mobile          60     0.660775
2      Tablet          35    -0.382554
3  Headphones          80     1.495437
4  Smartwatch          50     0.243443
5      Camera          15    -1.217216

In [ ]:
#now normalization for 3 columns
cols=['Price','Units_Sold','Discount']
df_norm=(df[cols] - df[cols].mean())/(df[cols].std())
print(df_norm)

      Price  Units_Sold  Discount
0  1.365931   -0.799885 -0.821638
1 -0.321396    0.660775  0.250064
2  0.160698   -0.382554 -0.392957
3 -1.189164    1.495437  1.321766
4 -0.899908    0.243443  0.893085
5  0.883838   -1.217216 -1.250319

In [ ]:
#Decimal Scaling
#table- convert into decimal scaling, pick up highst value divie by 10 ntil not less thn 1
df['Price_Decimal']=df['Price']/10000
print(df[['Product','Price','Price_Decimal']])
#cant be dont on thre columns caus highet values will be diff

      Product  Price  Price-Decimal
0      Laptop  55000            5.5
1      Mobile  20000            2.0
2      Tablet  30000            3.0
3  Headphones   2000            0.2
4  Smartwatch   8000            0.8
5      Camera  45000            4.5

In [ ]:
df['Unit_Decimal']=df['Units_Sold']/100
print(df[['Product','Units_Sold','Unit_Decimal']])

      Product  Units_Sold  Unit_Decimal
0      Laptop          25          0.25
1      Mobile          60          0.60
2      Tablet          35          0.35
3  Headphones          80          0.80
4  Smartwatch          50          0.50
5      Camera          15          0.15

Part B: Data Type Conversion

In [ ]:
import pandas as pd
import numpy as np
data = {
'Order_ID':[101,102,103,104,105,106],
'Customer_Gender':['Male','Female','Female','Male','Female','Male'],
'Payment_Method':['UPI','Credit Card','Debit Card','COD','UPI','Debit Card'],
'Product_Category':['Electronics','Clothing','Home','Electronics','Beauty','Electronics'],
'City':['Pune','Mumbai','Delhi','Bangalore','Pune','Hyderabad'],
'Order_Value':[4500,2300,3200,5200,1800,4100]
}
df = pd.DataFrame(data)
display(df)

,Order_ID,Customer_Gender,Payment_Method,Product_Category,City,Order_Value
0,101,Male,UPI,Electronics,Pune,4500
1,102,Female,Credit Card,Clothing,Mumbai,2300
2,103,Female,Debit Card,Home,Delhi,3200
3,104,Male,COD,Electronics,Bangalore,5200
4,105,Female,UPI,Beauty,Pune,1800
5,106,Male,Debit Card,Electronics,Hyderabad,4100

In [ ]:
#Method 1 :Label Encoding
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['Gender_Label']=le.fit_transform(df['Customer_Gender'])
df['City_Label']=le.fit_transform(df['City'])#gives values alphabetically

display(df)
#reverse encoding can be done too here male= 1 female=0
#label encdig can be done

,Order_ID,Customer_Gender,Payment_Method,Product_Category,City,Order_Value,Gender_Label,City_Label
0,101,Male,UPI,Electronics,Pune,4500,1,4
1,102,Female,Credit Card,Clothing,Mumbai,2300,0,3
2,103,Female,Debit Card,Home,Delhi,3200,0,1
3,104,Male,COD,Electronics,Bangalore,5200,1,0
4,105,Female,UPI,Beauty,Pune,1800,0,4
5,106,Male,Debit Card,Electronics,Hyderabad,4100,1,2

In [ ]:
#1 Method 2: One-Hot Encoding
df_encoded=pd.get_dummies(df,columns=['Payment_Method'])
display(df_encoded)
#one hot encoder
'''     cod cc dc upi
   cod 1    0   0  0
   cc  0    1   0  0
   deb  0   0   1  0
   upi 0    0   0  1'''

,Order_ID,Customer_Gender,Product_Category,City,Order_Value,Gender_Label,City_Label,Payment_Method_COD,Payment_Method_Credit Card,Payment_Method_Debit Card,Payment_Method_UPI
0,101,Male,Electronics,Pune,4500,1,4,False,False,False,True
1,102,Female,Clothing,Mumbai,2300,0,3,False,True,False,False
2,103,Female,Home,Delhi,3200,0,1,False,False,True,False
3,104,Male,Electronics,Bangalore,5200,1,0,True,False,False,False
4,105,Female,Beauty,Pune,1800,0,4,False,False,False,True
5,106,Male,Electronics,Hyderabad,4100,1,2,False,False,True,False

In [ ]:
#encodig multiple columns
df_multi=pd.get_dummies(df,columns=['Customer_Gender','City'])
display(df_multi)
#gender
'''   f   m
    f  1  0
    m  0  1

    but in label encoding female is 0'''

,Order_ID,Payment_Method,Product_Category,Order_Value,Gender_Label,City_Label,Customer_Gender_Female,Customer_Gender_Male,City_Bangalore,City_Delhi,City_Hyderabad,City_Mumbai,City_Pune
0,101,UPI,Electronics,4500,1,4,False,True,False,False,False,False,True
1,102,Credit Card,Clothing,2300,0,3,True,False,False,False,False,True,False
2,103,Debit Card,Home,3200,0,1,True,False,False,True,False,False,False
3,104,COD,Electronics,5200,1,0,False,True,True,False,False,False,False
4,105,UPI,Beauty,1800,0,4,True,False,False,False,False,False,True
5,106,Debit Card,Electronics,4100,1,2,False,True,False,False,True,False,False

In [ ]:
#dummy encoding
#instead of n+1 bit it will be n bit
#dummy encoding= label encoding for n=1

In [ ]:
#Method 3: Dummy Encoding(Drop First)
df_dummy=pd.get_dummies(df,columns=['Payment_Method'],drop_first=True)
display(df_dummy)

,Order_ID,Customer_Gender,Product_Category,City,Order_Value,Gender_Label,City_Label,Payment_Method_Credit Card,Payment_Method_Debit Card,Payment_Method_UPI
0,101,Male,Electronics,Pune,4500,1,4,False,False,True
1,102,Female,Clothing,Mumbai,2300,0,3,True,False,False
2,103,Female,Home,Delhi,3200,0,1,False,True,False
3,104,Male,Electronics,Bangalore,5200,1,0,False,False,False
4,105,Female,Beauty,Pune,1800,0,4,False,False,True
5,106,Male,Electronics,Hyderabad,4100,1,2,False,True,False

In [ ]:
#data normalization
import pandas as pd
df=pd.read_csv("/amazon_products_dataset_Expt-14.csv")
df

   Product_ID                 Product_Name  Price  Rating  Reviews  Units_Sold
0        P101               Wireless Mouse    799     4.3     1520         350
1        P102            Bluetooth Speaker   1499     4.5      980         220
2        P103                 USB Keyboard    699     4.1      870         180
3        P104               Gaming Headset   2499     4.6     2100         410
4        P105                   Smartwatch   3999     4.4     3050         520
5        P106                   Power Bank   1199     4.2     1750         390
6        P107                 Laptop Stand    899     4.0      620         140
7        P108                       Webcam   1899     4.3     1120         260
8        P109                 Portable SSD   5499     4.7     1850         330
9        P110             Wireless Charger    999     4.2      760         190
10       P111  Noise Cancelling Headphones   7999     4.6     4200         610
11       P112          Mechanical Keyboard   4599     4.5     2100         290
12       P113                 Gaming Mouse   1599     4.4     1300         340
13       P114                 Tablet Stand    699     4.1      540         120
14       P115                      USB Hub    899     4.2      870         200
15       P116          External Hard Drive   6499     4.6     2300         310
16       P117            Smartphone Tripod   1199     4.3      760         210
17       P118              Laptop Backpack   1999     4.4     1600         420
18       P119            Bluetooth Earbuds   2999     4.5     3500         530
19       P120                LED Desk Lamp   1299     4.3      980         260
20       P121                 Phone Holder    499     4.0      420         150
21       P122            Wireless Keyboard   2499     4.4     1450         310
22       P123             Portable Monitor   8999     4.6     1250         170
23       P124                   Smart Plug    799     4.2      720         210
24       P125                  WiFi Router   3499     4.5     2100         390
25       P126              Graphics Tablet   4599     4.4      980         160
26       P127                   VR Headset  12999     4.7     3100         140
27       P128                   Microphone   2199     4.3     1300         270
28       P129             Smart Light Bulb    699     4.2      880         240
29       P130           Laptop Cooling Pad   1499     4.3      990         260
30       P131                Action Camera   9999     4.6     2100         200
31       P132               Smart Doorbell   5999     4.5     1750         180
32       P133              Streaming Stick   3499     4.4     2500         430
33       P134           Portable Projector  11999     4.6     1450         120
34       P135                 Gaming Chair  15999     4.7     2100          90
35       P136               Desk Organizer    599     4.1      450         160
36       P137              USB Flash Drive    799     4.2      900         320
37       P138       Phone Screen Protector    299     4.0      600         380
38       P139                Laptop Sleeve    999     4.3      720         210
39       P140           Wireless Presenter   1499     4.4      520         130
40       P141         Tablet Keyboard Case   2999     4.5      850         150
41       P142             Smart Thermostat  10999     4.6     1200         110
42       P143              Security Camera   4999     4.4     2100         260
43       P144                 Drone Camera  24999     4.7     1800          70
44       P145              Electric Kettle   1999     4.3     1400         310
45       P146                    Air Fryer   7999     4.6     2200         200
46       P147                 Robot Vacuum  18999     4.5     1650         120
47       P148                  Smart Scale   2499     4.4      980         170
48       P149          Digital Photo Frame   3499     4.3      870         150
49       P150                 Portable Fan    999     4.2      760         240

In [ ]:
#min max  normalizaton (all)
cols1=['Price','Units_Sold','Rating','Reviews']
df_norm=(df[cols1] - df[cols1].min())/(df[cols1].max()-df[cols1].min())
display(df_norm)

       Price  Units_Sold    Rating   Reviews
0   0.020243    0.518519  0.428571  0.291005
1   0.048583    0.277778  0.714286  0.148148
2   0.016194    0.203704  0.142857  0.119048
3   0.089069    0.629630  0.857143  0.444444
4   0.149798    0.833333  0.571429  0.695767
5   0.036437    0.592593  0.285714  0.351852
6   0.024291    0.129630  0.000000  0.052910
7   0.064777    0.351852  0.428571  0.185185
8   0.210526    0.481481  1.000000  0.378307
9   0.028340    0.222222  0.285714  0.089947
10  0.311741    1.000000  0.857143  1.000000
11  0.174089    0.407407  0.714286  0.444444
12  0.052632    0.500000  0.571429  0.232804
13  0.016194    0.092593  0.142857  0.031746
14  0.024291    0.240741  0.285714  0.119048
15  0.251012    0.444444  0.857143  0.497354
16  0.036437    0.259259  0.428571  0.089947
17  0.068826    0.648148  0.571429  0.312169
18  0.109312    0.851852  0.714286  0.814815
19  0.040486    0.351852  0.428571  0.148148
20  0.008097    0.148148  0.000000  0.000000
21  0.089069    0.444444  0.571429  0.272487
22  0.352227    0.185185  0.857143  0.219577
23  0.020243    0.259259  0.285714  0.079365
24  0.129555    0.592593  0.714286  0.444444
25  0.174089    0.166667  0.571429  0.148148
26  0.514170    0.129630  1.000000  0.708995
27  0.076923    0.370370  0.428571  0.232804
28  0.016194    0.314815  0.285714  0.121693
29  0.048583    0.351852  0.428571  0.150794
30  0.392713    0.240741  0.857143  0.444444
31  0.230769    0.203704  0.714286  0.351852
32  0.129555    0.666667  0.571429  0.550265
33  0.473684    0.092593  0.857143  0.272487
34  0.635628    0.037037  1.000000  0.444444
35  0.012146    0.166667  0.142857  0.007937
36  0.020243    0.462963  0.285714  0.126984
37  0.000000    0.574074  0.000000  0.047619
38  0.028340    0.259259  0.428571  0.079365
39  0.048583    0.111111  0.571429  0.026455
40  0.109312    0.148148  0.714286  0.113757
41  0.433198    0.074074  0.857143  0.206349
42  0.190283    0.351852  0.571429  0.444444
43  1.000000    0.000000  1.000000  0.365079
44  0.068826    0.444444  0.428571  0.259259
45  0.311741    0.240741  0.857143  0.470899
46  0.757085    0.092593  0.714286  0.325397
47  0.089069    0.185185  0.571429  0.148148
48  0.129555    0.148148  0.428571  0.119048
49  0.028340    0.314815  0.285714  0.089947

In [ ]:
# z score normaization
cols=['Rating','Units_Sold','Reviews','Price']
df_norm=(df[cols] - df[cols].mean())/(df[cols].std())
display(df_norm)

      Rating  Units_Sold   Reviews     Price
0  -0.421580    0.812282  0.075943 -0.692019
1   0.606665   -0.260855 -0.577069 -0.557310
2  -1.449825   -0.591051 -0.710090 -0.711263
3   1.120787    1.307576  0.777327 -0.364869
4   0.092542    2.215615  1.926145 -0.076207
5  -0.935703    1.142478  0.354078 -0.615043
6  -1.963948   -0.921247 -1.012411 -0.672775
7  -0.421580    0.069341 -0.407770 -0.480334
8   1.634910    0.647184  0.475006  0.212455
9  -0.935703   -0.508502 -0.843111 -0.653531
10  1.120787    2.958556  3.316819  0.693559
11  0.606665    0.316988  0.777327  0.039258
12  0.092542    0.729733 -0.190099 -0.538066
13 -1.449825   -1.086345 -1.109154 -0.711263
14 -0.935703   -0.425953 -0.710090 -0.672775
15  1.120787    0.482086  1.019183  0.404897
16 -0.421580   -0.343404 -0.843111 -0.615043
17  0.092542    1.390125  0.172685 -0.461090
18  0.606665    2.298164  2.470321 -0.268648
19 -0.421580    0.069341 -0.577069 -0.595799
20 -1.963948   -0.838698 -1.254267 -0.749752
21  0.092542    0.482086 -0.008707 -0.364869
22  1.120787   -0.673600 -0.250563  0.886000
23 -0.935703   -0.343404 -0.891483 -0.692019
24  0.606665    1.142478  0.777327 -0.172428
25  0.092542   -0.756149 -0.577069  0.039258
26  1.634910   -0.921247  1.986609  1.655766
27 -0.421580    0.151890 -0.190099 -0.422601
28 -0.935703   -0.095757 -0.697998 -0.711263
29 -0.421580    0.069341 -0.564977 -0.557310
30  1.120787   -0.425953  0.777327  1.078442
31  0.606665   -0.591051  0.354078  0.308676
32  0.092542    1.472674  1.261039 -0.172428
33  1.120787   -1.086345 -0.008707  1.463325
34  1.634910   -1.333992  0.777327  2.233090
35 -1.449825   -0.756149 -1.217989 -0.730508
36 -0.935703    0.564635 -0.673812 -0.692019
37 -1.963948    1.059929 -1.036597 -0.788240
38 -0.421580   -0.343404 -0.891483 -0.653531
39  0.092542   -1.003796 -1.133339 -0.557310
40  0.606665   -0.838698 -0.734276 -0.268648
41  1.120787   -1.168894 -0.311027  1.270883
42  0.092542    0.069341  0.777327  0.116235
43  1.634910   -1.499090  0.414542  3.965063
44 -0.421580    0.482086 -0.069171 -0.461090
45  1.120787   -0.425953  0.898255  0.693559
46  0.606665   -1.086345  0.233150  2.810415
47  0.092542   -0.673600 -0.577069 -0.364869
48 -0.421580   -0.838698 -0.710090 -0.172428
49 -0.935703   -0.095757 -0.843111 -0.653531

In [ ]:
#decimal scaling
df['Price_Decimal']=df['Price']/100000
display(df[['Product_Name','Price','Price_Decimal']])

                   Product_Name  Price  Price_Decimal
0                Wireless Mouse    799        0.00799
1             Bluetooth Speaker   1499        0.01499
2                  USB Keyboard    699        0.00699
3                Gaming Headset   2499        0.02499
4                    Smartwatch   3999        0.03999
5                    Power Bank   1199        0.01199
6                  Laptop Stand    899        0.00899
7                        Webcam   1899        0.01899
8                  Portable SSD   5499        0.05499
9              Wireless Charger    999        0.00999
10  Noise Cancelling Headphones   7999        0.07999
11          Mechanical Keyboard   4599        0.04599
12                 Gaming Mouse   1599        0.01599
13                 Tablet Stand    699        0.00699
14                      USB Hub    899        0.00899
15          External Hard Drive   6499        0.06499
16            Smartphone Tripod   1199        0.01199
17              Laptop Backpack   1999        0.01999
18            Bluetooth Earbuds   2999        0.02999
19                LED Desk Lamp   1299        0.01299
20                 Phone Holder    499        0.00499
21            Wireless Keyboard   2499        0.02499
22             Portable Monitor   8999        0.08999
23                   Smart Plug    799        0.00799
24                  WiFi Router   3499        0.03499
25              Graphics Tablet   4599        0.04599
26                   VR Headset  12999        0.12999
27                   Microphone   2199        0.02199
28             Smart Light Bulb    699        0.00699
29           Laptop Cooling Pad   1499        0.01499
30                Action Camera   9999        0.09999
31               Smart Doorbell   5999        0.05999
32              Streaming Stick   3499        0.03499
33           Portable Projector  11999        0.11999
34                 Gaming Chair  15999        0.15999
35               Desk Organizer    599        0.00599
36              USB Flash Drive    799        0.00799
37       Phone Screen Protector    299        0.00299
38                Laptop Sleeve    999        0.00999
39           Wireless Presenter   1499        0.01499
40         Tablet Keyboard Case   2999        0.02999
41             Smart Thermostat  10999        0.10999
42              Security Camera   4999        0.04999
43                 Drone Camera  24999        0.24999
44              Electric Kettle   1999        0.01999
45                    Air Fryer   7999        0.07999
46                 Robot Vacuum  18999        0.18999
47                  Smart Scale   2499        0.02499
48          Digital Photo Frame   3499        0.03499
49                 Portable Fan    999        0.00999

In [ ]:
#decimal scalling for review
df['Review_Decimal']=df['Reviews']/10000
display(df[['Product_Name','Reviews','Review_Decimal']])

                   Product_Name  Reviews  Review_Decimal
0                Wireless Mouse     1520           0.152
1             Bluetooth Speaker      980           0.098
2                  USB Keyboard      870           0.087
3                Gaming Headset     2100           0.210
4                    Smartwatch     3050           0.305
5                    Power Bank     1750           0.175
6                  Laptop Stand      620           0.062
7                        Webcam     1120           0.112
8                  Portable SSD     1850           0.185
9              Wireless Charger      760           0.076
10  Noise Cancelling Headphones     4200           0.420
11          Mechanical Keyboard     2100           0.210
12                 Gaming Mouse     1300           0.130
13                 Tablet Stand      540           0.054
14                      USB Hub      870           0.087
15          External Hard Drive     2300           0.230
16            Smartphone Tripod      760           0.076
17              Laptop Backpack     1600           0.160
18            Bluetooth Earbuds     3500           0.350
19                LED Desk Lamp      980           0.098
20                 Phone Holder      420           0.042
21            Wireless Keyboard     1450           0.145
22             Portable Monitor     1250           0.125
23                   Smart Plug      720           0.072
24                  WiFi Router     2100           0.210
25              Graphics Tablet      980           0.098
26                   VR Headset     3100           0.310
27                   Microphone     1300           0.130
28             Smart Light Bulb      880           0.088
29           Laptop Cooling Pad      990           0.099
30                Action Camera     2100           0.210
31               Smart Doorbell     1750           0.175
32              Streaming Stick     2500           0.250
33           Portable Projector     1450           0.145
34                 Gaming Chair     2100           0.210
35               Desk Organizer      450           0.045
36              USB Flash Drive      900           0.090
37       Phone Screen Protector      600           0.060
38                Laptop Sleeve      720           0.072
39           Wireless Presenter      520           0.052
40         Tablet Keyboard Case      850           0.085
41             Smart Thermostat     1200           0.120
42              Security Camera     2100           0.210
43                 Drone Camera     1800           0.180
44              Electric Kettle     1400           0.140
45                    Air Fryer     2200           0.220
46                 Robot Vacuum     1650           0.165
47                  Smart Scale      980           0.098
48          Digital Photo Frame      870           0.087
49                 Portable Fan      760           0.076

In [ ]:
#Turnin categorical variables into uantitative variables
df=pd.read_csv('/Student-Dataset.csv')
display(df)

,Roll_No,Gender,Department,CGPA,Number_of_Backlogs,Attendance_Percentage,Placement_Status,Salary
0,101,Female,Computer,8.2,0,92,Placed,450000
1,102,Male,IT,7.5,1,85,Not Placed,0
2,103,Female,ENTC,9.1,0,96,Placed,550000
3,104,Male,Mechanical,6.8,2,78,Not Placed,0
4,105,Female,Computer,8.7,0,88,Placed,480000
5,106,Male,Civil,7.2,3,72,Not Placed,0
6,107,Female,IT,8.9,0,91,Placed,500000
7,108,Male,Computer,6.5,1,80,Not Placed,0
8,109,Female,ENTC,7.8,0,84,Placed,420000
9,110,Male,Mechanical,7.0,2,76,Not Placed,0

In [ ]:
#label encoding placement status
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['Placement_Label']=le.fit_transform(df['Placement_Status'])
#gives values alphabetically

display(df)

,Roll_No,Gender,Department,CGPA,Number_of_Backlogs,Attendance_Percentage,Placement_Status,Salary,Placement_Label
0,101,Female,Computer,8.2,0,92,Placed,450000,1
1,102,Male,IT,7.5,1,85,Not Placed,0,0
2,103,Female,ENTC,9.1,0,96,Placed,550000,1
3,104,Male,Mechanical,6.8,2,78,Not Placed,0,0
4,105,Female,Computer,8.7,0,88,Placed,480000,1
5,106,Male,Civil,7.2,3,72,Not Placed,0,0
6,107,Female,IT,8.9,0,91,Placed,500000,1
7,108,Male,Computer,6.5,1,80,Not Placed,0,0
8,109,Female,ENTC,7.8,0,84,Placed,420000,1
9,110,Male,Mechanical,7.0,2,76,Not Placed,0,0

In [ ]:
#one hot encoding-department
df_encoded=pd.get_dummies(df,columns=['Department'])
display(df_encoded)

,Roll_No,Gender,CGPA,Number_of_Backlogs,Attendance_Percentage,Placement_Status,Salary,Placement_Label,Department_Civil,Department_Computer,Department_ENTC,Department_IT,Department_Mechanical
0,101,Female,8.2,0,92,Placed,450000,1,False,True,False,False,False
1,102,Male,7.5,1,85,Not Placed,0,0,False,False,False,True,False
2,103,Female,9.1,0,96,Placed,550000,1,False,False,True,False,False
3,104,Male,6.8,2,78,Not Placed,0,0,False,False,False,False,True
4,105,Female,8.7,0,88,Placed,480000,1,False,True,False,False,False
5,106,Male,7.2,3,72,Not Placed,0,0,True,False,False,False,False
6,107,Female,8.9,0,91,Placed,500000,1,False,False,False,True,False
7,108,Male,6.5,1,80,Not Placed,0,0,False,True,False,False,False
8,109,Female,7.8,0,84,Placed,420000,1,False,False,True,False,False
9,110,Male,7.0,2,76,Not Placed,0,0,False,False,False,False,True

In [ ]:
#dummies- department
df_dummy=pd.get_dummies(df,columns=['Department'],drop_first=True)
display(df_dummy)

,Roll_No,Gender,CGPA,Number_of_Backlogs,Attendance_Percentage,Placement_Status,Salary,Placement_Label,Department_Computer,Department_ENTC,Department_IT,Department_Mechanical
0,101,Female,8.2,0,92,Placed,450000,1,True,False,False,False
1,102,Male,7.5,1,85,Not Placed,0,0,False,False,True,False
2,103,Female,9.1,0,96,Placed,550000,1,False,True,False,False
3,104,Male,6.8,2,78,Not Placed,0,0,False,False,False,True
4,105,Female,8.7,0,88,Placed,480000,1,True,False,False,False
5,106,Male,7.2,3,72,Not Placed,0,0,False,False,False,False
6,107,Female,8.9,0,91,Placed,500000,1,False,False,True,False
7,108,Male,6.5,1,80,Not Placed,0,0,True,False,False,False
8,109,Female,7.8,0,84,Placed,420000,1,False,True,False,False
9,110,Male,7.0,2,76,Not Placed,0,0,False,False,False,True